export const ADD_TODO = "ADD_TODO";
export const COMPLETE_TODO_SUCCESS = "COMPLETE_TODO_SUCCESS";
export const SET_FILTER = "SET_FILTER";
export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const FETCH_PRODUCTS_SUCCESS =
  "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE =
  "FETCH_PRODUCTS_FAILURE";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";